apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-jenkins-deployment
  labels:
    app: k8s-jenkins
spec:
  selector:
    matchLabels:
      app: k8s-jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8s-jenkins
    spec:
      serviceAccountName: default
      containers:
        - image: jenkins/jenkins
          name: k8s-jenkins-container
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: k8s-jenkins-persistent-storage
              mountPath: /var/lib/jenkins
      volumes:
        - name: k8s-jenkins-persistent-storage
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
